### ISSUE TITLE
the gan for low quality image？

### ISSUE THREAD

**Issue by brisyramshere** [liaohaofu/adn#8]
the generated artifact image and the original artifact image has a different，that the original artifacts always around with bone structure，but the generated artifacts not always around with the bone structure，this make discriminator easy to judge，and the generator tend to transfer artifact and bone structure together to normal image，and so the bone structure will also be removed together with artifacts。 

do you run into this problem？and how can I solve this？thank you！

**Comment by brisyramshere** [comment]
I think it is the side effect of the gan for low quality image， it will tend to make network treat the bone structure around artifacts also as artifacts

**Comment by liaohaofu** [comment]
Yes, this is the drawback of GAN based solution. There is currently no gaurantee that the output image will recover all the anatomical structure and only remove the artifacts. In our experiments, we do see that some bone structures, that look like the artifacts, be removed and transferred. The artifact transfer/removal are determined by the dataset and is learned in a data-driven fashion with GAN.

One way to solve this problem is to consider MAR in the sinogram/projection domain where only the metal traces are affected. We partially solved the problem in our [DudoNet paper](http://openaccess.thecvf.com/content_CVPR_2019/papers/Lin_DuDoNet_Dual_Domain_Network_for_CT_Metal_Artifact_Reduction_CVPR_2019_paper.pdf) with paired dataset.

**Comment by brisyramshere** [comment]
> Yes, this is the drawback of GAN based solution. There is currently no gaurantee that the output image will recover all the anatomical structure and only remove the artifacts. In our experiments, we do see that some bone structures, that look like the artifacts, be removed and transferred. The artifact transfer/removal are determined by the dataset and is learned in a data-driven fashion with GAN.
> 
> One way to solve this problem is to consider MAR in the sinogram/projection domain where only the metal traces are affected. We partially solved the problem in our [DudoNet paper](http://openaccess.thecvf.com/content_CVPR_2019/papers/Lin_DuDoNet_Dual_Domain_Network_for_CT_Metal_Artifact_Reduction_CVPR_2019_paper.pdf) with paired dataset.

thank you for your reply.I will go to see to see your new paper for more details.

And I think there is another drawback, is that the definition of artifact consistency loss.
Paper assumed that:
 artifacted_img = artifact + no_artifacted_img 
but i think it should be:
artifacted_img = no_artifacted_img - no_art_img_in_metal_trace +artifact
but art loss assumed that : 
artifacted_img1-no_artifacted_img1=artifacted_img2-no_artifacted_img2
that means:
no_art_img_in_metal_trace1=no_art_img_in_metal_trace2
it is not right，so I think it is the error of art loss。

Do you think it is a problem?And, is there any solution to address it?  Sorry for my poor english.

**Comment by liaohaofu** [comment]
Hi, this is a good point! One thing we could do is to compute the L1 loss only outside the metal region (which can be roughly estimated via thresholding). Let's assume a binary metal mask M where pixels outside the metal region are set to ones (and zeros otherwise). Then the loss can be updated as M*(
artifacted_img1-no_artifacted_img1)-M*(artifacted_img2-no_artifacted_img2). For this loss, we do not have any constraint on the metal region and rely on GAN loss to give better outputs. It would be interesting to see how it performs when compared with the original design.
